### ISSUE TITLE
No such file or directory on existing binary

### ISSUE THREAD

**Issue by sebastianbarfurth** [Microsoft/vscode-java-debug#154] opened 2017-11-13 10:45 UTC
**Platform:** macOS High Sierra 10.13.1

**VSCode version:** 1.18.0

I'm receiving the following error:

```
Failed to launch debuggee VM. Reason: java.io.IOException: Cannot run program "/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/bin/java" (in directory "/Users/sebastianbarfurth/Documents/Eclipse Workspace/TestProject"): error=2, No such file or directory
```

The project is an Eclipse project and I use ``Language Support for Java(TM) by Red Hat``. Language support works fine. Concerning the above errors, the mentioned file ``/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/bin/java`` does exist and is executable from the command line. I set my ``java.home`` in VSCode to the correct home also.

```
➜  ~ la -l /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/bin
total 2312
-rwxrwxr-x  1 root  wheel   101K Sep 14 11:55 java
...
```

Any idea what could be causing this?

PS. In case it's relevant, my launch.json is auto generated. My ``src/`` folder only contains ``Main.java``. You can find my launch.json: [/.vscode/launch.json](https://gist.github.com/sebastianbarfurth/fb6fd0826b86acb84677363692d86295)

**Comment by testforstephen** [comment] 2017-11-14 10:34
very weird. Cannot reproduce it in my mac. Can you try a sample maven project to see if it can be reproduced?

**Comment by sebastianbarfurth** [comment] 2017-11-14 10:39
The issue persists with a Maven project. Same error as well.

**Comment by andxu** [comment] 2017-12-11 09:20
Could you please upload a test.zip contains your simple project?

**Comment by akaroml** [comment] 2018-03-02 05:42
@sebastianbarfurth thanks for reporting. 
@andxu please provide steps to help the user try and troubleshoot. To me, the project setting is not clear though.

**Comment by andxu** [comment] 2018-03-02 06:59
Please give us your project structure(brew install tree if tree is not installed) and some system information :
`tree /Users/sebastianbarfurth/Documents/Eclipse\ Workspace/TestProject`
and then java version
`/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/bin/java -version`
and then java home
`echo $JAVA_HOME`

**Comment by andxu** [comment] 2018-04-24 04:05
DUP as https://github.com/redhat-developer/vscode-java/issues/400, solved at java language server side.

**Comment by andxu** [comment] 2018-04-24 04:07
Closing the wrong issue, reopen it again.

**Closed** 2018-08-07 02:15 UTC
Labels: bug, needs more info

**Comment by andxu** [comment] 2018-08-07 02:52
@sebastianbarfurth I cannot repro this issue using latest 0.11.0, can you try it again(this bug is auto-closed)?
