### ISSUE TITLE
Break point seems not continue and hang the thread in attach mode

### ISSUE THREAD

**Issue by adashen** [Microsoft/vscode-java-debug#374] opened 2018-08-22 09:19 UTC
[provide a description of the issue]

##### Environment
- Operating System: windows 10
- JDK version: jdk-10.0.2
- Visual Studio Code version: 1.26.1
- Java extension version: 0.29.0
- Java Debugger extension version: 0.11.0

##### Steps To Reproduce
1. pre-step:
    a. install iotedgehubdev : pip install iotedgehubdev
    b. install vs code edge extension
2. Run: Setup IoT Edge Simulator in VSCode
3. Download and open the project EdgeSolutionJavaEdge.zip from \\ZHANGCHEN\javasolution
4. Right click deployment.template.json -> Run "Build and Run IoT Edge Solution in Simulator"
5. Add some break point in App.java method EvantCallback.execute  and MessageCallbackMqtt.execute
. Choose debug config "<module> remote debug (Java)".
6. Choose remote debug configuration and attach the process
7. The break points will hit several times and then, it will not be hit again.
8. docker logs -f edgeHubDev
9. You will find errors like "System.TimeoutException: Message completion response not received". It is because the thread of "MessageCallbackMqtt" is hung, and the completion response is not sent

Besides, we use intelliJ to remote debug, everything works fine.

**Comment by adashen** [comment] 2018-08-27 05:53
![javadebugger_threadswitch](https://user-images.githubusercontent.com/1872137/44642829-8e5d4800-aa00-11e8-94c7-1d687d69410e.gif)

**Comment by adashen** [comment] 2018-08-27 05:54
Upload gif to demo. The two break points are in two threads. The break point could not switch between the two threads smoothly.

**Comment by testforstephen** [comment] 2018-12-13 10:32
The issue is fixed in vscode. Close it.

**Closed by testforstephen** 2018-12-13 10:32 UTC
Labels: external
