### ISSUE TITLE
Scroll Issue on Debug console

### ISSUE THREAD

**Issue by naveenroy001** [microsoft/vscode-java-debug#903] opened 2020-11-08 14:30 UTC
Hi,

Thanks for giving us such a great help to creating very nice and sophisticated environment to work. I am very grate full to your team.
I am Working on Java and getting lagging issue on debug console...when i scroll from mouse wheel to top its giving lagging issue..
lagging issue is like when you move from one line is continues showing same line again and again. please check this issue.

Thank you

**Comment by rura6502** [comment] 2020-11-12 05:54
I have same problem..

**Comment by testforstephen** [comment] 2020-11-12 09:58
it seems this is duplicated with the upstream issue https://github.com/microsoft/vscode/issues/107704

**Comment by testforstephen** [comment] 2020-12-07 07:03
The upstream VS Code is investigating the issue, and looks like they cannot reproduce the issue. 
@naveenroy001 @rura6502 would you mind sharing some reproduce steps there? thanks.

**Comment by naveenroy001** [comment] 2020-12-07 10:13
These are the steps to produce the issue.

1.) Start Visual Studio Code open any Java Project.
2.) Do Some Error Code.
3.) use Try catch to catch the error.
4.) use printStackTrace to print The error on Debug Console.
5.) Debug The project and run the error code. 
6.) Now go to Debug console... now scroll up you Console Window.

You will see the same line again and again.

**Comment by testforstephen** [comment] 2021-01-22 07:18
This is being fixed by the upstream https://github.com/microsoft/vscode/issues/107704, so closing this one.

**Closed by testforstephen** 2021-01-22 07:18 UTC
Labels: external
