### ISSUE TITLE
hover instance in debug mode don't show popup with details

### ISSUE THREAD

**Issue by vanmxpx** [Microsoft/vscode-java-debug#444] opened 2018-09-20 07:14 UTC
I have a problem since updated java debugger update. Whenever i tried to see what i have in variable when i debug an application the popup with its details don't shows.

Same issue was some time ago https://github.com/Microsoft/vscode-java-debug/issues/297

##### Environment
- Operating System: Windows 10
- JDK version: 1.8.0.152
- Visual Studio Code version: Vs Code 1.27.2 or VS Code Insiders 1.28.0
- Java extension version: 0.31.0
- Java Debugger extension version: 0.13.0

##### Steps To Reproduce
1. debug any java project
2. stop on breakpoint
3. hover variable

##### Current Result
Popup with variable details was not shown
##### Expected Result
must be popup with details

**Comment by andxu** [comment] 2018-09-20 09:06
Thank you to provide the snapshot, I will look at this issue.

**Comment by vanmxpx** [comment] 2018-09-20 09:07
@andxu thank you for you time

**Comment by vanmxpx** [comment] 2018-09-24 09:02
@andxu  Some updates
Popup start showing, if i just step out of variable
![image](https://user-images.githubusercontent.com/16278721/45944053-622dea80-bff1-11e8-9039-43d4a173bf5c.png)

But even i go to the next lines, again no popup
![image](https://user-images.githubusercontent.com/16278721/45944122-b1741b00-bff1-11e8-8f6e-79d2754c7d6f.png)

**Comment by andxu** [comment] 2018-09-26 12:05
@vanmxpx I can not  reproduce your problem, please open vscode settings and set java trace level and  java debug loglevel to verbose:
![image](https://user-images.githubusercontent.com/17075863/46078585-2d738c00-c1c7-11e8-9c92-8670dbb70df5.png)
![image](https://user-images.githubusercontent.com/17075863/46078615-48460080-c1c7-11e8-9a48-6b6c11b30c62.png)
and find the log by "Open java language server log" :
![image](https://user-images.githubusercontent.com/17075863/46078653-5f84ee00-c1c7-11e8-97ec-1a36acef9fcd.png)

Send me the request&reponse of evaluation like:
 {"command":"evaluate","arguments":{"expression":"\"test_lucene","frameId":14,"context":"hover"},"type":"request","seq":67}

{"success":false,"message":"Cannot evaluate because of compilation error(s): String literal is not properly closed by a double-quote.","request_seq":67,"command":"evaluate","body":{"error":{"id":2001,"format":"Cannot evaluate because of compilation error(s): String literal is not properly closed by a double-quote."}},"seq":79,"type":"response"}

**Comment by vanmxpx** [comment] 2018-09-26 13:11
Somehow it worked now properly
Probably, i found the solution

There is `node_modules` folder with a lot of files in my projects' source folder. (In gradle build i exclude it)
Also i noticed, what after couple of refreshes Java Server stops working properly

So i moved `node_modules` suggested, what Java Server trying to watch all this files.

But maybe it's just fixed with another update :)

**Comment by andxu** [comment] 2018-09-26 23:30
If you now work properly after removing node_modules,  I will close this issue.

**Comment by vanmxpx** [comment] 2018-09-27 07:29
No problems after that, thanks for helping

**Closed** 2018-09-27 07:50 UTC
