### ISSUE TITLE
Wrong classpath at runtime when the maven project is in a folder

### ISSUE THREAD

**Issue by dmarrazzo** [microsoft/vscode-java-debug#584] opened 2019-05-18 18:08 UTC
Launching vscode in the maven root folder, the debug is able to manage correctly the classpath.
Whereas when vscode is launched in the parent folder (that contains more maven projects) it fails to execute the project due to a wrong classpath evaluation.
In order to debug, I've added those lines at the beginning of the main:

```java
        try {
            Class.forName("org.drools.compiler.commons.jci.readers.ResourceReader");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        ClassLoader cl = EmbedMain.class.getClassLoader();

        URL[] urls = ((URLClassLoader) cl).getURLs();

        for (URL url : urls) {
            System.out.println(url.getFile());
        }
```

The output (attached) shows that the classpath is significantly different:

[parent.txt](https://github.com/redhat-developer/vscode-java/files/3194104/parent.txt)

[inner.txt](https://github.com/redhat-developer/vscode-java/files/3194105/inner.txt)

### Linked issue:
https://github.com/redhat-developer/vscode-java/issues/925

##### Environment
- Operating System: Linux Fedora 30
- JDK version: penjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

- Visual Studio Code version: 1.34
- Java extension version: 0.44.0
- pref
    "java.home": "/usr/lib/jvm/java-1.8.0-openjdk/",
    "java.jdt.ls.vmargs": "-noverify -Xmx3G -Xss128M -XX:+UseG1GC -XX:+UseStringDeduplication",

##### Steps To Reproduce
1. import projects:
https://gitlab.com/ba-demos/dmn-insurance/insurance-decision
https://gitlab.com/ba-demos/dmn-insurance/kie-client

2. install decision project

```bash
cd insurance-decision
mvn clean install
```

3. running the client from maven, it works as expected

```bash
mvn clean exec:java
```

4. Launch vscode inside `kie-client` project:

- execute `client.EmbedMain`
- the program runs with no error

5. Launch vscode in the parent folder of the `kie-client` project:

- open and execute the class: `client.EmbedMain`

##### Current Result
Loading failed because Cannot create instance of class: 

```
org.kie.pmml.assembler.PMMLAssemblerService
Exception in thread "main"
java.lang.ExceptionInInitializerError
	at org.kie.api.internal.utils.ServiceRegistry.getInstance(ServiceRegistry.java:27)
ServiceRegistry.java:27
	at org.kie.api.KieServices$Factory$LazyHolder.<clinit>(KieServices.java:341)
	at org.kie.api.KieServices$Factory.get(KieServices.java:348)
(...)
```

##### Expected Result
it runs with no error and completes with:

```
(...)
DMNResultImpl{context={
    PreviousIncidents: false
    Age: 28
    CarAge: 3
    Insurance Base Price: 1000
    Car reliability factor: function Car reliability factor( car age )
    FinalPrice: 1100.0
}
, messages=org.kie.dmn.core.util.DefaultDMNMessagesManager@102d92c4}
```

**Comment by minkir014** [comment] 2019-05-19 12:02
What's your `launch.json`? Please show it.

**Comment by dmarrazzo** [comment] 2019-05-19 20:03
Here it is:

```json
{
    "configurations": [
        {
            "type": "java",
            "name": "CodeLens (Launch) - EmbedMain",
            "request": "launch",
            "mainClass": "client.EmbedMain",
            "projectName": "kie-client"
        }
    ]
}
```

Thank you for looking into it.

**Comment by minkir014** [comment] 2019-05-20 13:17
If the project folder name is `kie-client`.
So set `mainClass` setting to `kie-client/client.EmbedMain` and `project Name` to `{workspace}/kie-client`.

**Comment by dmarrazzo** [comment] 2019-05-20 17:24
Hi @minkir014 ,
I think that it's not a config problem, but a bug.
Even because `launch.json` is generated by vscode and works fine for other similar projects with the same structure!
Nevertheless, I tested your suggestions:
```json
{
    "configurations": [
        {
            "type": "java",
            "name": "CodeLens (Launch) - EmbedMain",
            "request": "launch",
            "mainClass": "kie-client/client.EmbedMain",
            "projectName": "${workspaceFolder}/kie-client"
        }
    ]
}
```
It leads to: `Path for project must have only one segment.`

If you want to try on your own you can find the instruction to reproduce the problem in the first description.

Thank you

**Comment by dmarrazzo** [comment] 2019-05-20 17:26
Hi @testforstephen, could you please give your opinion on this issue?
Thank you

**Comment by testforstephen** [comment] 2019-05-21 02:10
i tried to clone these two sample projects into a parent folder dmn-insurance, and open it in VS Code, there are many unresolved maven dependencies `org.kie.x`.

btw, it may be better to use a parent pom.xml to manage the modules when you open a parent folder with multiple maven projects in VS Code.

**Comment by dmarrazzo** [comment] 2019-05-21 06:43
Hi @testforstephen , thank you for reviewing my problem.
Those projects are not modules, kie-client depends on the other one.
I'd like to get a functional parity with eclipse where I can have in the same workspace multiple unrelated projects (at least more than 1): for this reason I cannot create a parent pom.

Maybe you need to add Red Hat maven repo to resolve all the dependencies:
```xml
    <profile>
      <id>jboss-ga-profile</id>
      <repositories>
        <repository>
          <id>jboss-ga-repository</id>
          <url>https://maven.repository.redhat.com/ga/</url>
          <releases>
            <enabled>true</enabled>
          </releases>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <id>jboss-ga-plugin-repository</id>
          <url>https://maven.repository.redhat.com/ga/</url>
          <releases>
            <enabled>true</enabled>
          </releases>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
        </pluginRepository>
      </pluginRepositories>
    </profile>
```

**Comment by testforstephen** [comment] 2019-05-21 10:15
i can reproduce it. Looks like it doesn't add the dependencies of the referenced maven project `insurance-decision` to the runtime classpaths. This is a bug.

**Comment by dmarrazzo** [comment] 2019-05-21 14:08
Hi @testforstephen , I look forward to see it solved :-)
Thank you very much for your help!

**Comment by dmarrazzo** [comment] 2019-06-03 11:17
Hi! Any plan for solving this bug?
Thank you

**Comment by testforstephen** [comment] 2019-06-03 11:27
should be fixed in the next release 0.20.0

**Comment by testforstephen** [comment] 2019-06-10 09:45
java-debugger will exclude the classpaths from test scope when calculating the project's runtime classpaths. I saw you added `test` scope to many dependencies in the file `insurance-decision/pom.xml`. Removing these `test` tag works for me.

Is there any strong reason why `test` scope is needed?

**Comment by dmarrazzo** [comment] 2019-06-11 09:19
Hello @testforstephen, `test` scope makes sense because sometime you need some dependencies to run the tests that you don't want in the main project in order to keep in the right footprint.
Moreover, often you cannot change the dependencies in sub projects that are not under your direct control.
I also expect that vscode manages the dependencies as the maven / eclipse does: it would be a really nasty thing seeing in the pom "hack to workaround vscode limitation", wouldn't it?

Thank you

**Comment by testforstephen** [comment] 2019-06-11 10:33
> See the doc https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope.
>- test
This scope indicates that the dependency is not required for normal use of the application, and is only available for the test compilation and execution phases. This scope is not transitive.

Test scope is targeted for test purpose. If we include test scope dependencies to the normal application (run/debug the main class), it seems violating the purpose of test scope. Is it not?

**Comment by dmarrazzo** [comment] 2019-06-11 19:00
Hello @testforstephen . 
You are right, in a maven project there are two branches of code: `main` and `test` (both in `src` folder).
POM file defines through the `test` scope the dependencies that are relevant to the test branch.
So, the `test` scope dependencies must not included when I launch the code in the main branch, whereas if I run a JUnit test that is usually located in the test branch, the java classpath has to include all the `test` scope dependencies.
Again, I expect that it runs exactly like it does in maven via command line: `mvn exec:java`.
Nothing more, nothing less.
You can even import the maven project in eclipse: it manage the dependencies in the same way, and there are no problems. 
So it's something related to `vscode-java-debug` that it's not able to understand the `pom.xml` semantic correctly (or maybe the `.project` file, not sure on which it relies).
I've also noticed that `vscode-java-debug` is influenced by the dependencies order in the `pom.xml` file! In fact, if I move the following dependency down it works as expected:

```xml
		<dependency>
			<groupId>com.demo</groupId>
			<artifactId>InsuranceDecision</artifactId>
			<version>1.0-SNAPSHOT</version>
		</dependency>
```
Obviously, this is a clear evidence that the behaviour is not consistent.

Thank you

**Comment by testforstephen** [comment] 2019-06-12 03:22
1. When you run junit test, that's right, the `test` scope is needed to be in the classpath.
2. `mvn exec:java` has a `classpathScope` agument, it's `runtime` by default. It's similar as you open `kie-client` folder in VS Code directly. They both find `InsuranceDecision` dependency from the local maven repository, so it works. But when you open the parent folder in VS Code, the debugger will resolve `InsuranceDecision` dependency from the sub project `insurance-decision`.
3. When you move `InsuranceDecision` dependency down in the pom.xml, it works. This is a bug we're tracking (#566). The root cause is these two sub projects are using some same dependencies, but `insurance-decision` project marked them as `test` scope, and `kie-client` project used them as normal scope. When the debugger is resolving the program classpath, it did distinct and make the first finding dependency to be placed in the result. So when `InsuranceDecision` is in front, the shared dependencies with `test` scope are added to result. And in the last step, we filter out those classpath items with `test` scope from the result. This is why some dependencies are missed. This is our bug.

**Comment by dmarrazzo** [comment] 2019-06-12 08:15
Hi @testforstephen ,
thank you for the explanation.
So can I assume that when you will solve #566  it will address even my issue?
IMHO, the debugger should provide the same behaviour at runtime (same classpath) either the project is in the workspace root or it's at subfolder level, at least other IDEs work in this way.
I think that having multiple maven projects in the workspace and running them in isolation is an important feature: I'm not sure if this is already the goal of **vscode-java-debug**. I hope so!

**Comment by testforstephen** [comment] 2019-06-12 08:46
YES, Fix #566 will solve this issue, too. The debugger mistakenly excludes the shared dependencies by multiple projects if one of them marks it as `test` scope, this is the same root cause for these two issues.

Finally, it should have same behavior as `eclipse` and `mvn exec:java`.
- Run a main class in src/main/java, exclude test classes and include all dependencies with `runtime` scope.
- Run class in src/test/java, add `test` scope.

**Comment by dmarrazzo** [comment] 2019-06-12 09:01
Thank you very much. I will wait the next release and confirm the final resolution!
Great job!

**Comment by minkir014** [comment] 2019-06-12 13:21
When will you intend to fix that issue #556 and subsequently this issue??

**Comment by testforstephen** [comment] 2019-06-14 09:01
The fix is on the way.

**Closed** 2019-06-17 11:20 UTC
Labels: bug

**Comment by spulci** [comment] 2019-06-20 12:43
@testforstephen have you got a release date? Thanks

**Comment by testforstephen** [comment] 2019-06-27 01:30
@spulci i plan to have a release earlier next week.

**Comment by testforstephen** [comment] 2019-07-02 02:34
A new release is ready in vscode marketplace. Have a try!

**Comment by dmarrazzo** [comment] 2019-07-02 14:18
it works for me! Cool. Thank you so much

**Comment by spulci** [comment] 2019-07-02 15:07
> A new release is ready in vscode marketplace. Have a try!
> 
> //@spulci @dmarrazzo @minkir014

Thank you so much!! Great release!! Works fine! ;)

**Comment by emmanuelBayle** [comment] 2019-07-04 09:30
Hello, since the last update all dependencies with a <classifier> are no longer included in the classpath when I try to debug my app.
My current workarround is to directly add the desired jar in the .classpath of my sub-module but it's not ideal.
I didn't have problems with the 0.19.0 version

**Comment by testforstephen** [comment] 2019-07-04 10:06
@emmanuelBayle could you share a sample project to help reproduce the issue?

**Comment by emmanuelBayle** [comment] 2019-07-04 10:50
@testforstephen not easily, I'll try to make you one.
