### ISSUE TITLE
Buttons disabled

### ISSUE THREAD

**Issue by wpfeiffe** [Microsoft/vscode-java-debug#411] opened 2018-09-06 10:59 UTC
Issue Type: <b>Bug</b>

Write a small Hello World java app with several lines.  Set a breakpoint on first line.  Start debugging.  After the first break point is hit, press step over button in Debug Toolbar.  At this point the Step Over, Step Into, Step Out Of buttons are all incorrectly disabled and the Play button changed to a Pause.  You can press the Pause to re-enable other buttons.  

This behavior continues through out the debug session.

The expected behavior after the first Step Over operation is that the other Step buttons remain enabled and DON'T require the press of Pause to continue debugging.

Extension version: 0.12.2
VS Code version: Code 1.27.0 (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-05T05:22:06.672Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.74GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_5248257|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by testforstephen** [comment] 2018-09-06 11:54
i just tried in latest VSCode, the debug toolbar is correctly displayed. Anyway my platform is win 10. Let me try Mac later.

**Comment by wpfeiffe** [comment] 2018-09-06 12:46
Let me try a new simple HelloWorld app and make sure I can reproduce it.

**Comment by wpfeiffe** [comment] 2018-09-06 13:59
Tried the same HelloWorld project on my Windows 10 and my Macbook.  Window
10 version works as expected, MacOS version shows the same problematic
behavior described in my bug report.  Must be a MacOS thing.

**Comment by andxu** [comment] 2018-09-08 07:46
@dancecoder Could you please provide the errors in problem view?

**Comment by dancecoder** [comment] 2018-09-08 11:39
Unfortunately Developer console has no errors.
My steps for reproduce:
1. create a simple project with pom.xml
2. create a class and test class with a test method (I use JUnit).
3. build the project with maven
4. togle a break point in the test class or the project class
5. Click the debug test gray label above the test method
6. click Step Over on debug-actions-widget (once or few times)
   got: debugging looks paused (the Step Over button is disabled)
   expected: not paused and ready for Step Over
7. make rounded eyes and click Pause on debug-actions-widget
   got: unpaused and ready for Step Over
Repeat from point 6 until you eyes is not squere

environment:
kubuntu 18.4
VSCode 1.27.1
vscode-java-debugger 0.12.2
vscode-java-test 0.8.0
vscode-maven 0.10.0
redhat.java 0.30.0
editorconfig 0.12.4
all settings (except editorconfig) is default

As I wrote I got this behavior after vscode update to latest version. Let me know if I able to change some option to provide some additional information.

**Comment by dancecoder** [comment] 2018-09-08 11:57
I've changed java.debug.level to info and got the next error in DeveloperConsole
  ERR Cannot read property 'lineNumber' of null: TypeError: Cannot read property 'lineNumber' of null
	at Object.e.to (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:692:25)
	at e.provideHover (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:749:117)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:763:824
	at e._withAdapter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:761:91)
	at e.$provideHover (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:763:786)
	at e._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:681:309)
	at e._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:681:27)
	at e._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:679:802)
	at e._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:678:993)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:677:791
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:98:597
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:99:917)
	at a (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:164:787)
	at Socket._socketDataListener (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)

not sure is it related to this current problem. After i have changed line feeds to crlf (it was lf) this message is gone

**Comment by Fubuchi** [comment] 2018-09-09 16:33
On windows 10 version 1803 build 17134.228, the bug is not always occur, some time it does, some time it doesn't. Downgrade vscode to 1.26.0 temporary fix the problem.

**Comment by aleeraser** [comment] 2018-09-11 14:13
I can confirm the same issue on mac.

**Comment by Sindisil** [comment] 2018-09-13 20:50
I'm seeing the same issue on Windows 10, with both Java 8 and 10, and VSC 1.27.2 and 1.28.0-insider. Debugger for Java 0.12.2, Java lang support 0.30.0.

**Comment by alex-cornejo** [comment] 2018-09-13 22:14
I get the same error on Ubuntu 18. vscode 1.26 is working fine, you should get back to this version until this bugg get fixed.

**Comment by joshryanne** [comment] 2018-09-13 23:33
was able to duplicate on my machine:
windows 10.
vscode 1.27
debugger 0.12.0

problem went away when i reverted to vscode 1.26.1 as suggested.

**Comment by adrianmoya** [comment] 2018-09-14 21:39
I just hit this annoying issue. 
Ubuntu 18.04
VSCode 1.27.2
Debugger 0.12.2

Start a debuggin session, buttons get disabled after 1st breakpoint, the only way to continue is pausing the debuggin session and restarting to the next breakpoint

**Comment by testforstephen** [comment] 2018-09-19 10:39
Through the discussion with VS Code team, the StoppedEvent should be sent after StepResponse or ContinueResponse. So we submit a fix to fix the StoppedEvent order. This fix works well for single thread scenario. But for multiple threads scenario, the debug buttons disabled issue is still probably existing.  We're communicating back to VS Code team about the new scenario.

The new release 0.13.0 with the fix is just released, in case you want to have a try. And please let us know if you found new issues. Thanks.

**Comment by wpfeiffe** [comment] 2018-09-19 19:46
Just tried it with simple Hello World java debug and with Spring Boot java
remote debug.  Both work fine.   Debug toolbar buttons stay enabled
throughout the session.

Thanks

**Comment by testforstephen** [comment] 2018-09-20 01:32
@wpfeiffe Thanks for the verification.

**Comment by testforstephen** [comment] 2018-09-25 05:31
VS Code team has pushed a fix for the multiple threads scenario, it's in the 2018-09-20 insider. And i verified it works. Close this issue first. If you guys find the issue is still not resolved, welcome to reopen it.

**Closed by testforstephen** 2018-09-25 05:31 UTC
