### ISSUE TITLE
No delegateCommandHandler for vscode.java.startDebugSession when starting Debugger

### ISSUE THREAD

**Issue by dsyer** [microsoft/vscode-java-debug#728] opened 2019-12-10 16:06 UTC
Try to run project. Error popup just like here:
https://github.com/Microsoft/vscode-java-debug/blob/master/Troubleshooting.md#no-delegatecommandhandler-for-vscodejavastartdebugsession-when-starting-debugger

The links to run main classes and tests never show up in the source code either. The Java LSP server says it is running. No obvious errors.

##### Environment
- Operating System: Gitpod
- JDK version: OpenJDK Runtime Environment 18.9 (build 11.0.5+10)
- Visual Studio Code version: Gitpod
- Java extension version: Gitpod
- Java Debugger extension version: Gitpod

##### Steps To Reproduce
1. Open any Java project. E.g. https://gitpod.io/#https://github.com/spring-projects/spring-petclinic
2. Go to Debug->Start Debugging

**Comment by testforstephen** [comment] 2019-12-16 04:20
It looks like the extension is not loaded correctly. Could you share us the language server log file?

Below is the command to get the log file:
**F1 -> Java: Open Java language server log file**

**Comment by dsyer** [comment] 2019-12-16 07:32
Here's the log: [lsp.log](https://github.com/microsoft/vscode-java-debug/files/3966544/lsp.log)

I also fixed the URL to link to the project workspace if you want to try it yourself.

**Comment by testforstephen** [comment] 2019-12-20 02:04
i didn't find any exception in the log file, so does the issue disappears in your workspace?

**Comment by testforstephen** [comment] 2019-12-20 02:13
i saw the **Language Support for Java** extension is an old version 0.47.0 in gitpod.io, that may be the reason. Because we have an important fix about "**No delegateCommandHandler for**" error in [vscode-java 0.49.0](https://github.com/redhat-developer/vscode-java/blob/master/CHANGELOG.md#0490-september-18th-2019).

**Comment by testforstephen** [comment] 2019-12-20 06:18
I would close this issue first. If you still reproduce it in the latest vscode-java extension, please reopen it.

**Closed by testforstephen** 2019-12-20 06:18 UTC
