### ISSUE TITLE
Plugin uninstall error

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#24] opened 2017-09-20 05:36 UTC
OS: Windows 10
Build: https://vscjavaci.cloudapp.net/job/vscode-java-debug.vsix/16/Azure/
VSCode: 1.16.1 x86
JDK: 1.8.0.14 x64

Repro Steps:

1. Click uninstall java Debug Extension for Visual Studio Code
2. Choose All in following dialog

![image](https://user-images.githubusercontent.com/22470312/30628015-4fd9e72a-9e06-11e7-9892-919c36c84e15.png)

![image](https://user-images.githubusercontent.com/22470312/30628056-97aeb8c8-9e06-11e7-95d2-28e1cc2255ce.png)

[Error - 10:23:54 PM] Sep 19, 2017 10:18:52 PM An internal error occurred during: "Periodic workspace save.".
org/eclipse/core/runtime/Plugin$2
java.lang.NoClassDefFoundError: org/eclipse/core/runtime/Plugin$2
	at org.eclipse.core.runtime.Plugin.savePluginPreferences(Plugin.java:385)
	at org.eclipse.core.internal.resources.SaveManager.saveMetaInfo(SaveManager.java:1310)
	at org.eclipse.core.internal.resources.SaveManager.save(SaveManager.java:1233)
	at org.eclipse.core.internal.resources.SaveManager.save(SaveManager.java:1165)
	at org.eclipse.core.internal.resources.DelayedSnapshotJob.run(DelayedSnapshotJob.java:52)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.ClassNotFoundException: org.eclipse.core.runtime.Plugin$2 cannot be found by org.eclipse.core.runtime_3.13.0.v20170207-1030
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more

**Comment by bsaby** [comment] 2017-10-10 10:07
OS: Windows 10
Build: 43
VSCode: 1.17.0 (x86/x64)
JDK: 1.8.0.14 x64
uninstall plugin:
![image](https://user-images.githubusercontent.com/22470312/31381017-c7393d7c-ade5-11e7-831b-8932d50eb225.png)

**Comment by akaroml** [comment] 2017-10-26 03:55
This issue is not tracked and was closed by bots at vscode side. @yaohaizh please check the vscode side to see whether further fix is needed.

**Comment by akaroml** [comment] 2017-10-26 03:56
Microsoft/vscode#34794

**Comment by yaohaizh** [comment] 2017-10-26 08:33
The original is fixed. 

For this one, it will pop up about the file is been locked, which is a common handling mechanism for locked resources that found on windows/linux. 

So close this issue as by design.

**Closed by yaohaizh** 2017-10-26 08:33 UTC
Labels: bug, external

**Comment by gamsim** [comment] 2018-05-02 05:44
Uninstall Java Extension Pack first if you want to uninstall Java Debug
