### ISSUE TITLE
HCR breakpoint reinstall doesn't work

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode-java-debug#198] opened 2017-12-19 04:18 UTC
In a valid method, if i add a new line such as `String a = "test";`, the HCR actually works, but the breakpoints after this line will be removed by HCR.

**Comment by yaohaizh** [comment] 2017-12-21 04:08
The issue is that when setBreakpoint from VSCode, it will send out before the document is saved. In this case, our status is not correctly set on the UI. Thus, the HCR reinstall failed for invalid breakpoint.

**Comment by testforstephen** [comment] 2017-12-21 06:32
Create a bug for vscode https://github.com/Microsoft/vscode/issues/40620

**Comment by yaohaizh** [comment] 2018-01-22 06:44
This issue had been fixed in the latest master branch.

**Closed by yaohaizh** 2018-01-22 06:44 UTC
Labels: bug
