### ISSUE TITLE
Java language server starting all the time in vs code

### ISSUE THREAD

**Issue by yaohaizh** [microsoft/vscode-java-debug#238] opened 2018-02-22 02:04 UTC
From internal user. 

 >Hey, are you aware of an issue from any of the VS Code Java extensions where the java language server >starts and kills perf in code? I’m seeing this happening a lot and I’m not using any Java when it happens. >The lag is happening at really inopportune times especially when creating a debugger configuration. I’m >considering moving the Java stuff to the experimental instance, or isolate it somehow as its impacting >everything else.

We need investigate whether the issue related to the debug configuration generation or by java language server.

**Comment by robotdad** [comment] 2018-02-23 01:35
Here is a screenshot of what I'm seeing.
![image](https://user-images.githubusercontent.com/1429895/36573567-8441cce8-17f6-11e8-8299-dd8d0c675b3b.png)

This is happening when I go to the debug mode and click add configuration. The problem is I'm editing C++ (or other files) and not Java when this occurs. When this occurs it causes the UI to not respond until the language service spins up. I'm just trying to create a c++ launch file but the Java extension is slowing it down.

**Comment by akaroml** [comment] 2018-02-26 04:03
@robotdad Could you share the workspace (screenshots or directory/file list) to help us investigate?

The Java language support should be activated when:
1. A Java file is opened
2. There is a pom.xml file in the root folder of your workspace
3. User switched to Java language manually

Does any of those cover your case?

**Comment by andxu** [comment] 2018-03-02 08:09
need to be fixed at Vscode side, see discussions at https://github.com/Microsoft/vscode/issues/33803 and https://github.com/Microsoft/vscode/issues/37918  and https://github.com/Microsoft/vscode/issues/39696 https://github.com/Microsoft/vscode/issues/37929, in short, it is caused by introducing onDebugInitialConfigurations and onDebugResolve https://github.com/Microsoft/vscode/issues/39677, need to be fixed at vscode side for declarative value in package.json

**Comment by andxu** [comment] 2018-03-02 08:28
Unfortunately, we use DebugConfigurationProvider to provide run-time initial debug configuration, which makes both our extension/java language server activated.
> 
@weinand commented on Nov 11, 2017

Most debug extensions contribute initial launch configs statically and declaratively through the package.json. In this case the DebugConfigurationProvider.provideDebugConfigurations isn't used and we could avoid the activation.

**Comment by andxu** [comment] 2018-03-20 02:39
We can do little since vscode activates us at the early stage where I think a new declarative in package.json should be provided by vscode declaring we provides java runtime  configuration.

**Comment by andxu** [comment] 2018-04-19 04:14
@roalexan Have you noticed that the new vscode-java has improved on the startup speed and ui to decrease the influence conflicting with other languages, eg: c++

**Comment by j-james** [comment] 2018-10-12 17:32
I too am having this problem, it's stuck at 37%. This happened after upgrading gradle with `./gradle wrapper`, then rebooting.

**Comment by akaroml** [comment] 2019-07-15 04:45
Time to actually fix this. @Eskibear

**Comment by Eskibear** [comment] 2019-07-15 05:43
The root cause is the dependency of the [Java Extension (vscode-java)](https://github.com/redhat-developer/vscode-java). Whenever the debugger is activated (e.g. here when user presses F5, vscode needs to activate all debugger extensions to get available config templates), it activates Java Extension as well. 

I think the solution would be:
- Remove the hard-coded extension dependency of vscode-java
- Check the activation status of vscode-java whenever it need to call upsteaming APIs. If vscode-java is not activated (indicating no Java project is found in current workspace), the debugger should simply mute itself.

With the proposed solution above, for the case mentiond in  https://github.com/microsoft/vscode-java-debug/issues/238#issuecomment-367881632 , the Java Debugger related entries would not appear, and of course the vscode-java extension would not be activated as well.

**Comment by testforstephen** [comment] 2019-08-22 07:40
The commit is merged.

**Closed by testforstephen** 2019-08-22 07:40 UTC
Labels: bug
