### ISSUE TITLE
Failed to resolve classpath: Main class 'org.example.test.Test' doesn't exist in the workspace.

### ISSUE THREAD

**Issue by clankill3r** [Microsoft/vscode-java-debug#89] opened 2017-10-11 21:34 UTC
I created a workspace like this:

<img width="720" alt="screen shot 2017-10-11 at 23 27 55" src="https://user-images.githubusercontent.com/738650/31468083-9893b19e-aedc-11e7-9832-ed75f4566273.png">

I get the following error:

> Failed

 to resolve classpath: Main class 'org.example.test.Test' doesn't exist in the workspace.

What am I doing wrong?

**Comment by testforstephen** [comment] 2017-10-12 09:34
@clankill3r The debugger doesn't support package structure for simple java folder yet, you should put Test.java to the root folder and remove org.example.test package declaration. Or open a maven/eclipse/gradle project to try the debugger, because the debugger supports those mature projects more friendly.

**Comment by clankill3r** [comment] 2017-10-12 11:03
I tried that and it is extremely bugged.

This project works fine:
<img width="1060" alt="screen shot 2017-10-12 at 12 58 02" src="https://user-images.githubusercontent.com/738650/31492931-59b8e662-af4d-11e7-948f-d7275a322508.png">

With this one I get "Error: Could not find or load main class Test"
<img width="1025" alt="screen shot 2017-10-12 at 12 58 30" src="https://user-images.githubusercontent.com/738650/31492949-69179478-af4d-11e7-966e-c4078af1cc0b.png">

Apart from the root path both projects are identical.

**Comment by clankill3r** [comment] 2017-10-12 11:10
The maven project works fine however. But I do hope we can go without a maven/eclipse/gradle in the future.

**Comment by testforstephen** [comment] 2017-10-13 01:21
This is a know issue that we're fixing. The reason is that the language server doesn't compile the Test.java in background. The workaround is that you modify the Test.java file and that'll trigger the incremental build to generate the Test.class in cache.

@ansyral Please take a look at this issue.

**Comment by clankill3r** [comment] 2017-10-13 11:25
I tried that but it does not seem to work. Anyway, I hope a solution will
come soon. For now I will use a maven project.


2017-10-13 3:21 GMT+02:00 Jinbo Wang <notifications@github.com>:

**Comment by akaroml** [comment] 2017-10-16 05:20
@clankill3r #94 is created for this scenario. We'll be working on supporting debugging source code without a project.

**Comment by yaohaizh** [comment] 2017-12-05 05:34
@clankill3r The debugger should have support single file without project. Please try it on the latest vscode-java/vscode-java-degger and let's know the result.

**Comment by gijswijs** [comment] 2017-12-05 06:11
@yaohaizh I tried to debug a single file, but to no avail. I tried it with JDK8 and JDK9 with debug 0.4.0, because this post made me think that could matter.

https://blogs.msdn.microsoft.com/visualstudio/2017/11/10/run-and-debug-java-9-in-visual-studio-code/

- But either way I get the error: Cannot read property 'openConfigFile' of undefined
- Cannot resolve main class automatically, please specify the mainClass (e.g. [mymodule/]com.xyz.MainClass) in the launch.json.

I don't get the dialog where you can choose the class, as the gif in the linked post suggests.

**Comment by yaohaizh** [comment] 2017-12-05 06:18
@gijswijs Could you try the same steps on the VSCode insider version?  The first issue might related to VSCode bugs itself.

**Comment by testforstephen** [comment] 2017-12-05 06:23
@gijswijs What's your JDK version?  In JDK 9, there is a known NPE bug when auto resolving the main class. https://github.com/Microsoft/vscode-java-debug/issues/125

**Comment by gijswijs** [comment] 2017-12-05 13:30
@yaohaizh I tried it with VScode insider and JDK8, and it's now possible to debug a single file. Thanks for the support!

**Comment by clankill3r** [comment] 2017-12-12 17:45
It works!!
How can I provide a jar files?
I tried:

```
 "args": "-classpath /Users/doekewartena/.m2/repository/org/processing/core/3.3.5"
```
and:
```
"args": "-classpath /Users/doekewartena/.m2/repository/org/processing/core/3.3.5/core-3.3.5.jar"
```
But that does not work.
Also I would prefer a way that intelliSense works.
Hope this is possible or would be possible in the future.

**Comment by gijswijs** [comment] 2017-12-14 06:35
I just confirmed that this now also works in the regular VSCode.

**Comment by yaohaizh** [comment] 2017-12-14 06:49
Thanks. Close this as it resolved.

**Closed by yaohaizh** 2017-12-14 06:49 UTC
Labels: bug

**Comment by BinniZenobioCordovaLeandro** [comment] 2019-10-31 23:09
> ¡¡Funciona!!
> ¿Cómo puedo proporcionar un archivo jar?
> Lo intenté:
> 
> ```
>  "args": "-classpath /Users/doekewartena/.m2/repository/org/processing/core/3.3.5"
> ```
> 
> y:
> 
> ```
> "args": "-classpath /Users/doekewartena/.m2/repository/org/processing/core/3.3.5/core-3.3.5.jar"
> ```
> 
> Pero eso no funciona.
> También preferiría una forma en que intelliSense funcione.
> 
> También probé un `.classpath`archivo en la raíz:
> 
> ```
> <? versión xml = " 1.0 " codificación = " UTF-8 " ?>
> < classpath >
>     < classpathentry  kind = " lib "  ruta = " /Users/doekewartena/.m2/repository/org/processing/core/3.3.5/core-3.3.5.jar " />
> </ classpath >
> ```
> 
> Espero que esto sea posible o sea posible en el futuro.
> Realmente estoy buscando una forma en la que no tenga que usar maven o eclipse o lo que sea para configurar un proyecto java simple.

![image](https://user-images.githubusercontent.com/42467277/67992134-9bc82080-fc09-11e9-81b5-a8fa54ad6dd1.png)
