### ISSUE TITLE
Running the contributed command: 'java.execute.workspaceCommand' failed.

### ISSUE THREAD

**Issue by RayJinStduio** [microsoft/vscode-java-debug#1023] opened 2021-06-20 06:31 UTC
[provide a description of the issue]

##### Environment
- Operating System: win10 21h1
- JDK version: 16.0.1
- Visual Studio Code version: 1.57.1
- Java extension version: 0.16.0
- Java Debugger extension version: 0.34.0

##### Issues
When running a Java Program ,I get the following error:
![image](https://user-images.githubusercontent.com/41432965/122664466-1fb29000-d1d4-11eb-8684-8a7fa2ded5fd.png)

##### Additional Informations
The error message in the log is:

!ENTRY org.eclipse.jdt.ls.core 4 0 2021-06-20 14:26:02.815
!MESSAGE Error in calling delegate command handler
!STACK 0
java.lang.reflect.InaccessibleObjectException: Unable to make boolean sun.nio.fs.WindowsFileAttributes.isDirectoryLink() accessible: module java.base does not "opens sun.nio.fs" to unnamed module @6259914a
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.eclipse.core.internal.filesystem.local.nio.DosHandler.isDirectoryLink(DosHandler.java:80)
	at org.eclipse.core.internal.filesystem.local.nio.DosHandler.fetchFileInfo(DosHandler.java:61)
	at org.eclipse.core.internal.filesystem.local.LocalFileNativesManager.fetchFileInfo(LocalFileNativesManager.java:65)
	at org.eclipse.core.internal.filesystem.local.LocalFile.fetchInfo(LocalFile.java:161)
	at org.eclipse.core.filesystem.provider.FileStore.fetchInfo(FileStore.java:260)
	at org.eclipse.core.internal.utils.FileUtil.realPath(FileUtil.java:129)
	at org.eclipse.core.internal.utils.FileUtil.realURI(FileUtil.java:184)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.setLocation(FileSystemResourceManager.java:1051)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.getStoreRoot(FileSystemResourceManager.java:578)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.locationURIFor(FileSystemResourceManager.java:813)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.allPathsForLocationNonCanonical(FileSystemResourceManager.java:82)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.allPathsForLocation(FileSystemResourceManager.java:70)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.allResourcesFor(FileSystemResourceManager.java:229)
	at org.eclipse.core.internal.resources.WorkspaceRoot.findFilesForLocationURI(WorkspaceRoot.java:97)
	at org.eclipse.core.internal.resources.WorkspaceRoot.findFilesForLocationURI(WorkspaceRoot.java:90)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.findResource(JDTUtils.java:1004)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.resolveCompilationUnit(JDTUtils.java:181)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.resolveCompilationUnit(JDTUtils.java:165)
	at com.microsoft.java.debug.plugin.internal.ResolveMainMethodHandler.resolveMainMethods(ResolveMainMethodHandler.java:66)
	at com.microsoft.java.debug.plugin.internal.JavaDebugDelegateCommandHandler.executeCommand(JavaDebugDelegateCommandHandler.java:76)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:502)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by testforstephen** [comment] 2021-06-21 01:30
Could you share some reproduce steps? It's better to share a minimum sample project.

**Comment by RayJinPersonalStudio** [comment] 2021-06-21 02:54
When I set JDK for language server to jdk11, the plug-in can work normally, but when it is set to jdk16, that error occurs.
![image](https://user-images.githubusercontent.com/41432965/122701030-f569dc80-d27e-11eb-88fb-de53180774dd.png)

**Comment by RayJinPersonalStudio** [comment] 2021-06-21 03:02
I just created a no build tools project
![image](https://user-images.githubusercontent.com/41432965/122701549-10891c00-d280-11eb-8ef1-b59b782ddee5.png)

**Comment by krlm** [comment] 2021-11-30 09:40
@testforstephen I've encountered similar problem, it happens when project is accessed through the path which contains a directory  symlink (Windows "SYMLINKD" aka soft link). It happened to me when I've switched to from JDK 14.0.1 to JDK 17.0.1 (both Corretto and OpenJDK are presenting the same error). When I'm opening project using direct path it works ok. 
I guess it's not a problem with `vscode-java-debug` itself but haven't found time to dig it deeper.

**Comment by testforstephen** [comment] 2021-12-01 06:31
The debugger will reuse the upstream JDT tool to resolve the Java model, looks like it doesn't take care of symlink on Windows well. Need take a look on the upstream first.

**Comment by testforstephen** [comment] 2021-12-27 03:50
@RayJinStduio @krlm Could you try to append `"--add-opens=java.base/sun.nio.fs=ALL-UNNAMED"` to the existing [VS Code setting](https://code.visualstudio.com/docs/getstarted/settings) `"java.jdt.ls.vmargs"`?

e.g. change it to the following value.

`
"java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m --add-opens=java.base/sun.nio.fs=ALL-UNNAMED"
`

**Comment by RayJinStduio** [comment] 2021-12-28 02:43
> @RayJinStduio @krlm Could you try to append `"--add-opens=java.base/sun.nio.fs=ALL-UNNAMED"` to the existing [VS Code setting](https://code.visualstudio.com/docs/getstarted/settings) `"java.jdt.ls.vmargs"`?
> 
> e.g. change it to the following value.
> 
> `"java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m --add-opens=java.base/sun.nio.fs=ALL-UNNAMED"`
I've tried this method. It's very useful for my.

**Comment by testforstephen** [comment] 2021-12-28 06:57
@RayJinStduio thanks for verification.

Duplicates with https://github.com/redhat-developer/vscode-java/issues/2264. This is a bug that will be fixed in vscode-java repo. 

The reason is that VS Code Java extension uses some internal JDK API `sun.nio.fs.WindowsFileAttributes.isDirectoryLink()` on Windows to check if your workspace contains symbolic directory. And using internal JDK APIs will throw illegal access by default when running on JDK 16 and above. See [JEP 396: Strongly Encapsulate JDK Internals by Default](https://openjdk.java.net/jeps/396) of [JDK 16 Release Notes](https://openjdk.java.net/projects/jdk/16/). 

The JVM args `"--add-opens=java.base/sun.nio.fs=ALL-UNNAMED"` is used to enable the access.

**Comment by krlm** [comment] 2021-12-30 08:38
@testforstephen it works for me too. Thanks for your help.

**Comment by testforstephen** [comment] 2022-07-04 05:00
Closing it since the upstream issue https://github.com/redhat-developer/vscode-java/issues/2264 has been fixed.

**Closed by testforstephen** 2022-07-04 05:00 UTC
Labels: external, launch, JPMS, symlink
