### ISSUE TITLE
No variables shown in VARIAVLES when debug `7.variableperformance` project

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/vscode-java-debug#736] opened 2019-12-25 09:35 UTC
Regression issue.

##### Environment
- Operating System: Mac 10.15.2
- JDK version: 13.0.1
- Visual Studio Code version: 1.41.1
- Java extension version: 0.55.1
- Java Debugger extension version: 0.24.0

##### Steps To Reproduce

1. Right-click java file with the main method
2. Click debug

##### Current Result
![image](https://user-images.githubusercontent.com/41051257/71441158-40af3780-273b-11ea-982c-cf8950c8942b.png)

##### Expected Result
![image](https://user-images.githubusercontent.com/41051257/71441190-60466000-273b-11ea-8367-5fdef757cc0d.png)

##### Additional Informations
Debug with this entry will occur this issue. Click `F5` to debug no this issue.
![image](https://user-images.githubusercontent.com/41051257/71441239-a4396500-273b-11ea-97f6-3d4cb3ad05e9.png)

![image](https://user-images.githubusercontent.com/41051257/71441243-a8658280-273b-11ea-8e35-57dfaffaf60d.png)

![image](https://user-images.githubusercontent.com/41051257/71441245-abf90980-273b-11ea-8059-ca990c4bbfdb.png)

![image](https://user-images.githubusercontent.com/41051257/71441247-b0252700-273b-11ea-925a-407a2a99030d.png)

**Comment by testforstephen** [comment] 2019-12-25 10:02
Cannot reproduce it, please provide the logs.

**Comment by ZhengJun003** [comment] 2019-12-26 06:49
```
!SESSION 2019-12-25 22:30:59.118 -----------------------------------------------
eclipse.buildId=unknown
java.version=13.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Command-line arguments:  -data /Users/user/Library/Application Support/Code/User/workspaceStorage/0bbee8981eebcfe3955bf8ebc6eea9af/redhat.java/jdt_ws

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:02.184
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:02.438
!MESSAGE Main thread is waiting

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:02.490
!MESSAGE >> initialize

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:02.492
!MESSAGE Initializing Java Language Server 0.49.1.201912231651

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:02.531
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:02.533
!MESSAGE Non-Static Commands: [java.edit.organizeImports, java.project.updateSourceAttachment, java.project.removeFromSourcePath, java.project.listSourcePaths, java.project.resolveSourceAttachment, java.project.addToSourcePath]

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:02.534
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:02.534
!MESSAGE Non-Static Commands: [vscode.java.checkProjectSettings, vscode.java.isOnClasspath, vscode.java.fetchUsageData, vscode.java.validateLaunchConfig, vscode.java.resolveMainMethod, vscode.java.resolveClasspath, vscode.java.resolveBuildFiles, vscode.java.resolveMainClass, vscode.java.updateDebugSettings, vscode.java.buildWorkspace, vscode.java.startDebugSession, vscode.java.inferLaunchCommandLength, vscode.java.resolveElementAtSelection]

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:02.562
!MESSAGE >> initialized

!ENTRY org.eclipse.core.net 1 0 2019-12-25 22:31:02.603
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:02.638
!MESSAGE Creating the Java project jdt.ls-java-project

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:05.057
!MESSAGE Finished creating the Java project jdt.ls-java-project

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:06.249
!MESSAGE Importing Eclipse project(s)

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:06.322
!MESSAGE Workspace initialized in 3779ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:06.438
!MESSAGE >> initialization job finished

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:06.447
!MESSAGE >> workspace/didChangeConfiguration

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:06.510
!MESSAGE >> java/buildWorkspace (full)

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:06.560
!MESSAGE >> New configuration: {java={home=/Library/java/javavirtualmachines/jdk-13.0.1.jdk/contents/Home, jdt={ls={vmargs=-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication}}, errors={incompleteClasspath={severity=warning}}, configuration={checkProjectSettingsExclusions=true, updateBuildConfiguration=interactive, maven={userSettings=null}}, trace={server=off}, import={maven={enabled=true}, gradle={enabled=true, wrapper={enabled=true}, version=null, arguments=null, jvmArguments=null, home=null}, exclusions=[**/node_modules/**, **/.metadata/**, **/archetype-resources/**, **/META-INF/maven/**]}, maven={downloadSources=false, updateSnapshots=false}, referencesCodeLens={enabled=false}, signatureHelp={enabled=false}, implementationsCodeLens={enabled=false}, format={enabled=true, settings={url=null, profile=null}, comments={enabled=true}, onType={enabled=true}}, saveActions={organizeImports=false}, project={referencedLibraries=[lib/**/*.jar]}, contentProvider={preferred=null}, autobuild={enabled=true}, maxConcurrentBuilds=1.0, completion={maxResults=50.0, enabled=true, overwrite=true, guessMethodArguments=false, favoriteStaticMembers=[org.junit.Assert.*, org.junit.Assume.*, org.junit.jupiter.api.Assertions.*, org.junit.jupiter.api.Assumptions.*, org.junit.jupiter.api.DynamicContainer.*, org.junit.jupiter.api.DynamicTest.*, org.mockito.Mockito.*, org.mockito.ArgumentMatchers.*, org.mockito.Answers.*], filteredTypes=[java.awt.*, com.sun.*], importOrder=[java, javax, com, org]}, foldingRange={enabled=true}, progressReports={enabled=true}, codeGeneration={hashCodeEquals={useJava7Objects=false, useInstanceof=false}, useBlocks=false, generateComments=false, toString={template=${object.className} [${member.name()}=${member.value}, ${otherMembers}], codeStyle=STRING_CONCATENATION, skipNullValues=false, listArrayContents=true, limitElements=0.0}}, selectionRange={enabled=true}, showBuildStatusOnStart={enabled=false}, debug={logLevel=warn, settings={showHex=false, showStaticVariables=false, showQualifiedNames=false, showLogicalStructure=true, showToString=true, maxStringLength=0.0, hotCodeReplace=manual, enableRunDebugCodeLens=true, forceBuildBeforeLaunch=true, console=integratedTerminal}}}}

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:06.562
!MESSAGE >> document/didOpen

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:07.867
!MESSAGE >> document/documentSymbol

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:07.875
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:07.883
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:07.885
!MESSAGE >> document/foldingRange

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:08.921
!MESSAGE >> document/codeAction

!ENTRY java-debug 1 0 2019-12-25 22:31:10.223
!MESSAGE Starting com.microsoft.java.debug.plugin

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:10.759
!MESSAGE Reconciled 0. Took 583 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:11.123
!MESSAGE begin problem for /VariablePerfTest.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:11.124
!MESSAGE 0 problems reported for /VariablePerfTest.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:11.125
!MESSAGE Validated 1. Took 200 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:11.141
!MESSAGE >> build jobs finished

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:11.147
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:11.148
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:11.158
!MESSAGE >> watchers registered

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:17.097
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:17.104
!MESSAGE >> workspace/executeCommand vscode.java.isOnClasspath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:17.135
!MESSAGE >> workspace/executeCommand vscode.java.updateDebugSettings

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:17.145
!MESSAGE >> java/buildWorkspace (incremental)

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:18.250
!MESSAGE >> workspace/executeCommand vscode.java.validateLaunchConfig

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:18.254
!MESSAGE >> workspace/executeCommand vscode.java.resolveClasspath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:18.284
!MESSAGE >> workspace/executeCommand vscode.java.checkProjectSettings

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:18.381
!MESSAGE >> workspace/executeCommand vscode.java.inferLaunchCommandLength

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:18.389
!MESSAGE >> workspace/executeCommand vscode.java.startDebugSession

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:20.083
!MESSAGE >> workspace/executeCommand vscode.java.fetchUsageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:26.820
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:26.825
!MESSAGE >> workspace/executeCommand vscode.java.isOnClasspath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:26.844
!MESSAGE >> java/buildWorkspace (incremental)

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:27.852
!MESSAGE >> workspace/executeCommand vscode.java.validateLaunchConfig

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:27.854
!MESSAGE >> workspace/executeCommand vscode.java.resolveClasspath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:27.873
!MESSAGE >> workspace/executeCommand vscode.java.checkProjectSettings

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:28.015
!MESSAGE >> workspace/executeCommand vscode.java.inferLaunchCommandLength

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:28.017
!MESSAGE >> workspace/executeCommand vscode.java.startDebugSession

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:28.987
!MESSAGE >> workspace/executeCommand vscode.java.fetchUsageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:30.903
!MESSAGE >> document/didClose

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:31.243
!MESSAGE >> document/didOpen

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:31.490
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:31.491
!MESSAGE >> document/documentSymbol

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:31.492
!MESSAGE >> document/foldingRange

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:31.493
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:33.484
!MESSAGE Reconciled 0. Took 1589 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:35.844
!MESSAGE begin problem for /TooManyVariables.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:35.844
!MESSAGE 0 problems reported for /TooManyVariables.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:35.845
!MESSAGE Validated 1. Took 1959 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:36.352
!MESSAGE >> document/didClose

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:36.427
!MESSAGE >> document/didOpen

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:36.444
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:36.447
!MESSAGE >> document/documentSymbol

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:36.784
!MESSAGE >> document/foldingRange

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:36.785
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:36.786
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:36.920
!MESSAGE Reconciled 0. Took 36 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:37.454
!MESSAGE begin problem for /VariablePerfTest.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:37.454
!MESSAGE 0 problems reported for /VariablePerfTest.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:37.456
!MESSAGE Validated 1. Took 132 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:38.707
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:38.712
!MESSAGE >> workspace/executeCommand vscode.java.isOnClasspath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:38.727
!MESSAGE >> java/buildWorkspace (incremental)

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:39.742
!MESSAGE >> workspace/executeCommand vscode.java.validateLaunchConfig

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:39.746
!MESSAGE >> workspace/executeCommand vscode.java.resolveClasspath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:39.756
!MESSAGE >> workspace/executeCommand vscode.java.checkProjectSettings

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:39.912
!MESSAGE >> workspace/executeCommand vscode.java.inferLaunchCommandLength

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:39.915
!MESSAGE >> workspace/executeCommand vscode.java.startDebugSession

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:41.343
!MESSAGE >> document/didClose

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:41.559
!MESSAGE >> document/didOpen

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:41.709
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:41.710
!MESSAGE >> document/documentSymbol

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:41.712
!MESSAGE >> document/foldingRange

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:41.738
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:42.831
!MESSAGE Reconciled 0. Took 719 ms

!ENTRY java-debug 4 0 2019-12-25 22:31:44.817
!MESSAGE [error response][variables]: Timeout occurred while waiting for packet 125.
!STACK 0
org.eclipse.jdi.TimeoutException: Timeout occurred while waiting for packet 125.
	at org.eclipse.jdi.internal.connect.PacketReceiveManager.getReply(PacketReceiveManager.java:196)
	at org.eclipse.jdi.internal.connect.PacketReceiveManager.getReply(PacketReceiveManager.java:207)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:195)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:230)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:262)
	at org.eclipse.jdi.internal.ReferenceTypeImpl.fields(ReferenceTypeImpl.java:939)
	at org.eclipse.jdi.internal.ReferenceTypeImpl.allFields(ReferenceTypeImpl.java:779)
	at com.microsoft.java.debug.core.adapter.variables.VariableUtils.hasChildren(VariableUtils.java:61)
	at com.microsoft.java.debug.core.adapter.handler.VariablesRequestHandler.handle(VariablesRequestHandler.java:233)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.lambda$dispatchRequest$0(DebugAdapter.java:87)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1183)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2306)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.dispatchRequest(DebugAdapter.java:86)
	at com.microsoft.java.debug.core.adapter.ProtocolServer.dispatchRequest(ProtocolServer.java:118)
	at com.microsoft.java.debug.core.protocol.AbstractProtocolServer.lambda$new$0(AbstractProtocolServer.java:78)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:44.911
!MESSAGE begin problem for /TooManyVariables.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:44.912
!MESSAGE 0 problems reported for /TooManyVariables.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:44.913
!MESSAGE Validated 1. Took 1674 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:48.739
!MESSAGE >> workspace/executeCommand vscode.java.fetchUsageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:31:50.392
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-25 22:32:06.141
!MESSAGE >> document/didClose

```

**Comment by testforstephen** [comment] 2020-07-15 03:29
Will close it. Feel free to reopen it once you reproduce it again.

**Closed by testforstephen** 2020-07-15 03:29 UTC
Labels: cannot repro
