### ISSUE TITLE
Empty space in project path causes error reading MANIFEST.MF in startup .jar

### ISSUE THREAD

**Issue by pascallaliberte** [microsoft/vscode-java-debug#677] opened 2019-09-28 14:37 UTC
When an empty space is found in a directory name as part of the project's path, starting debug produces an error saying one or more items in the class path are missing.

    The Class-Path manifest attribute in /private/var/folders/ln/b514t2f96mb7my4nmydx3dm80000gp/T/cp_54jeosbt017pmc6v0lb8gv4qe.jar referenced one or more files that do not exist:
    file:/Users/work/Project%20Path/project-name/target/classes/

It turns out that the first entry in the MANIFEST.MF file found in the startup .jar will be for the project's `target/classes` directory. Empty spaces in the project's path will be replaced with `%20` characters, causing the problem.

    Manifest-Version: 1.0
    Class-Path: file:/Users/work/Project%20Path/project-name/target/classes/

##### Environment
- Operating System: MacOS 10.14.6
- JDK version: jdk1.8.0_151
- Visual Studio Code version: 1.38.1 (commit b37e54c98e1a74ba89e03073e5a3761284e3ffb0)
- Java extension version: 0.8.0 (extension pack)
- Java Debugger extension version: 0.22.0

##### Steps To Reproduce

1. Make sure your project's path is in a directory which includes an empty space
2. Run debug
3. While running, extract the contents of the .jar file, and inspect the MANIFEST.MF file

e.g. to extract the contents of cp_54jeosbt017pmc6v0lb8gv4qe.jar

    jar xf cp_54jeosbt017pmc6v0lb8gv4qe.jar

In `META-INF/`, you'll find MANIFEST.MF

##### Current Result

MANIFEST.MF will include as its first item a directory path to the project's `target/classes` with a `%20` character replacing the empty space

##### Expected Result

I'm not sure which character should be used instead, of whether the parser for the MANIFEST.MF should be updated to correctly interpret the %20.

**Comment by testforstephen** [comment] 2019-09-29 02:59
Thanks for reporting this issue. 

>MANIFEST.MF will include as its first item a directory path to the project's target/classes with a %20 character replacing the empty space

In MANIFEST.MF file, we use URL to encode the absolute path, and `%20` is the right escape character for white space. 

I tried the empty space case, it works in the normal maven project, but reproduced it in spring-petclinic project.  After a look at this issue, i found there are duplicated issues in https://github.com/spring-projects/spring-boot/issues/11057, https://github.com/spring-projects/spring-boot/issues/10111, https://youtrack.jetbrains.com/issue/IDEA-178585. 

Here is the finding:
Currently java debugger will generate the manifest jar with the absolute path, it looks like spring-boot has some check at this file, and print the message `The Class-Path manifest attribute in cp_54jeosbt017pmc6v0lb8gv4qe.jar referenced one or more files that do not exist`.  And from my try, this message seems just a warning, the application still works.

**Comment by testforstephen** [comment] 2019-09-29 03:24
Created an issue in https://github.com/spring-projects/spring-boot/issues/18410 for more discussion.

**Comment by wilkinsona** [comment] 2019-10-03 14:14
We should probably do something in Spring Boot to correctly handle `%20`-encoded spaces, but I think a change in VS Code is also warranted as the use of absolute URLs isn't spec compliant. From the [jar file specification](https://docs.oracle.com/javase/8/docs/technotes/guides/jar/jar.html#classpath):

> The manifest for an application can specify one or more relative URLs referring to the JAR files and directories for other libraries that it requires. These relative URLs are treated relative to the code base from which the containing application was loaded.
>
> An application (or, more generally, a JAR file) specifies the relative URLs of the libraries that it requires with the manifest attribute Class-Path.
>
> …
>
> Currently, the URLs must be relative to the code base of the JAR file for security reasons.

In reality, implementations do appear to support absolute paths but I think it would be better to align with the spec.

**Comment by testforstephen** [comment] 2019-10-08 04:52
Ack. Using manifest jar to shorten the classpath is only recommended for java 8. And for java 9 and above, we would suggest to use argsfile to shorten the classpath. Given java 8 is approaching to end of update, we don't have plan to change it to relative path for manifest jar yet.

**Comment by testforstephen** [comment] 2019-10-08 04:53
The upstream spring-boot has fixed this issue, close it.

**Closed by testforstephen** 2019-10-08 04:53 UTC
Labels: external
