### ISSUE TITLE
Unrecognized option: --enable-preview

### ISSUE THREAD

**Issue by Tnze** [microsoft/vscode-java-debug#666] opened 2019-09-22 00:43 UTC
I cannot run the hello world and got `Unrecognized option: --enable-preview` .

##### Environment
- Operating System: MacOS
- JDK version: 10.0.2

##### Steps To Reproduce
1. Create file Tnze.java
2. 
```java
class Tnze {
    public static void main(String[] args) {
        System.out.println("hello world");
    }
}
```
3. Run

##### Current Result
```
bash-3.2$ /Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:56046 --enable-preview -Dfile.encoding=UTF-8 -cp "/Users/Tnze/Library/Application Support/Code/User/workspaceStorage/124fa978b4fe2ddb55450b012d43e56b/redhat.java/jdt_ws/tnze_29124188/bin" Tnze 
Unrecognized option: --enable-preview
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
bash-3.2$ 
```

**Comment by testforstephen** [comment] 2019-09-23 08:54
Looks like your workspace is opened in jdk 12 before. Could you try to run VS Code command `Java: Clean the Java language server workspace`?

**Comment by Tnze** [comment] 2019-09-23 09:26
Thanks, it works now. Is this a bug?d

**Comment by testforstephen** [comment] 2019-09-23 09:32
by design, when switching the jdk, you need clean the workspace cache. Generally, if you switch the jdk via `java.home` user settings, the java extension will prompt you to clean the workspace to restart. But if you did it offline, then you need manually do that.

**Comment by testforstephen** [comment] 2019-09-23 09:33
i will close it. However, if you want to continue the discussion, feel free to reopen it.

**Closed by testforstephen** 2019-09-23 09:33 UTC

**Comment by Tnze** [comment] 2019-09-24 16:43
谢谢解答，不过就是Github上你关了issue的话我这边就不能reopen啦^_^

**Comment by cvvishalkumar** [comment] 2020-07-01 15:09
> Looks like your workspace is opened in jdk 12 before. Could you try to run VS Code command `Java: Clean the Java language server workspace`?

Even I had the same issue and it resolved... Thanks a ton.
