### ISSUE TITLE
program args doesn't support Chinese

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#58] opened 2017-09-26 06:17 UTC
![image](https://user-images.githubusercontent.com/17075863/30845312-65dfd41c-a2c5-11e7-9172-6355b3f170e8.png)

**Comment by testforstephen** [comment] 2017-10-17 02:43
Cannot reproduce it, @andxu What's the encoding type of your project.

**Comment by andxu** [comment] 2017-10-24 10:33
This bug refers the problem of the encoding in the source file and the encoding in  the compiled class file and the encoding settings during run-time,  any mismatch of it will cause messy code. The eclipse ide provides full control of these encoding settings, I think we can simplify it in vscode through encoding settings in project level.

**Comment by andxu** [comment] 2017-11-14 07:26
The encoding is utf-8 for the launch.json, the source file, there is no way of  reading Chinese arguments in java.

**Comment by yaohaizh** [comment] 2018-03-21 03:16
@andxu, @testforstephen  I think we have fixed the encoding problems?  If cannot fix this, close it as designed.

**Comment by testforstephen** [comment] 2018-04-09 08:53
Duplicated with bug https://github.com/Microsoft/vscode-java-debug/issues/234, see the comments there for workaround.

**Closed by testforstephen** 2018-04-09 08:53 UTC
Labels: bug, needs more info
