### ISSUE TITLE
VSCode will not generate annotations when running tests

### ISSUE THREAD

**Issue by kjq** [microsoft/vscode-java-debug#1314] opened 2023-03-19 04:08 UTC
VSCode does not generate annotation when "launch before build" or "building using the Java Projects" view.  

I have been having a problem with VSCode, in test cases, where my "annotations" are not getting generated _only_ when I run/launch before build a test case (or if i manually build the project using the Java Projects view).

**Scenarios**:
- Run a test case with "launch before build" - nothing is generated under generated-sources/annotations
- Run Clean Workspace from the Java Projects tree - nothing is generated under generated-sources/annotations
- Run Rebuild Project from the Java Projects - nothing is generated under generated-sources/annotations
- Run Rebuild All from the Java Projects - nothing is generated under generated-sources/annotations
- Run mvn from the command-line - everything works.

Even though VSCode will show 100's of errors the test still runs and can be debugged in the editor. Everything else also seems to work fine.

I've been trying to reproduce this but have not been able to with a small example yet.

Referencing this issue: `https://github.com/microsoft/vscode-java-debug/issues/1232`

**Comment by testforstephen** [comment] 2023-03-30 06:22
Since you're using mapstruct for annotation generation, could you take a look at the issue
https://github.com/redhat-developer/vscode-java/issues/3007?

**Comment by kjq** [comment] 2023-03-30 14:35
If I understand correctly, the solution above with MapStruct was to "move" the SPI piece into a separate Maven dependency.  We are not creating any special implementations around the SPI.  If the suggestion is to move the mappings themselves into another Maven dependency then that is not really possible since they sit, purposely, within the module using them.

Even though VSCode flag everything as errors I _can_ debug and run the code.

At the very least, it seems that I can no longer disable the `forceBuildBeforeLaunch` and I have made the change across _all_ of my settings as far as I know.  At least when that didnt build during testing I could build outside in the CLI and then debug without all the errors.

```
"java.autobuild.enabled": false,
"java.debug.settings.forceBuildBeforeLaunch": false,
```

Also, pretty sure, but it has been a while, that debugging "did work" with `foceBuildBeforeLaunch` as long as I compiled outside of VSCode _if_ the mappings were changed but everything else was fine.

The reason this is an issue is because we do not change the mappings that often but we do change other code and having to remember to build outside is sort of painful (but would be acceptable at this point).

**Comment by testforstephen** [comment] 2023-03-31 06:46
`forceBuildBeforeLaunch` only takes effect when the autobuild setting is enabled, and it is used to avoid duplicated building. But if autobuild is disabled, we still force a build before launching.

A workaround for you is to use attach debugging instead of launching mode. See https://github.com/microsoft/vscode-java-debug/issues/120#issuecomment-417269773, you can configure a task in tasks.json to build the project and use maven command to run the application, then attach a debugger to it.

**Comment by kjq** [comment] 2023-03-31 12:50
Just to clarify, I have no problems using VSCode to attach to a running instance, started outside of VSCode, and debug.  That works fine.  My issue is when I want to run one or all tests and additionally, debug from a specific test.  

I am confused on the settings - autobuild is disabled.  What is the purpose of `forceBuildBeforeLaunch` then?  It used to not build the code when that was disabled.

**Comment by testforstephen** [comment] 2023-03-31 14:06
> Maybe a better question from my side so I understand, if we are using Maven and that works fine, locally and in CI, what is VSCode Java triggering for the build - does it not rely on the Maven lifecycle?

The Java extension relies on a middleware m2e to resolve and build Maven projects, which is expected to provide the same behavior as the command line Maven tool. Here it seems that m2e failed to handle your mapstruct annotation generation plugin, which is a bug on m2e. We need you to provide more information to help us understand your annotation use case. It would be helpful if you could provide a sample project for us to reproduce the issue.

**Comment by kjq** [comment] 2023-04-03 12:42
Im trying to put together a reproducer.  The problem is I do not seem to easily be able to replicate it with a simpler Maven multi-module project.

**Comment by kjq** [comment] 2023-04-07 17:44
Trying to work through a reproducer and I noticed this:

When I use `<maven.compiler.parameters>true</maven.compiler.parameters>` and build at the command-line the parameters are named.  When I build using Java Projects inside VSCode they are _not_.  If I instead set that using `<parameters>true</parameters> in the compiler plugin they are.

For whatever reason though it works in my sample so far but not our project (which is much larger)

[mapstruct.zip](https://github.com/microsoft/vscode-java-debug/files/11180519/mapstruct.zip)

**Comment by kjq** [comment] 2023-04-07 21:20
Finally!  It has taken me all day to do this.  Attached is a reproducer which shows the problem.  Even though I do not have a test case this is essentially the same problem when I run an actual test case. 

Even though it shows errors only in VSCode tests can still be run or debugged, it works perfectly fine outside of VSCode and in CI. Maven-wise, this has not changed very much and at one time running the tests _did_ work.

If you unzip the package:

1. Run `mvn clean install` from the command-line, it will compile fine without warnings.
2. Open the project in VSCode, select the `reproducer-testing` project in the Java Projects and then`Rebuild All` (or `Rebuild Project`) and it will give the errors about the parameters.

![Screenshot 2023-04-07 171312](https://user-images.githubusercontent.com/533810/230679786-0422d99d-0371-4a5c-ba3e-ee49f8f34760.png)

[reproducer.zip](https://github.com/microsoft/vscode-java-debug/files/11181607/reproducer.zip)

> As a note, I cobbled this together piece-by-piece.  The "AbstractMapperTest" is essentially a class actual mapper tests would implement.

**Comment by kjq** [comment] 2023-08-25 13:55
Has anyone had a chance to look at this?  It really is starting to affect being able to use VSCode, especially testing/debugging, with a large Java project.  Should I file this ticket somewhere else to get eyes on it?

**Comment by testforstephen** [comment] 2023-08-28 05:32
```
"java.autobuild.enabled": false,
"java.debug.settings.forceBuildBeforeLaunch": false,
```
>Also, pretty sure, but it has been a while, that debugging "did work" with foceBuildBeforeLaunch as long as I compiled outside of VSCode if the mappings were changed but everything else was fine.

I relaxed the restriction on forceBuildBeforeLaunch setting, and allow it to take effect even if autobuild is disabled. It has been in 0.54.0 pre-release version.

**Comment by testforstephen** [comment] 2023-08-29 06:49
Version 0.54.0 has been released. As a workaround, you can disable the autobuild and turn off the forceBuildBeforeLaunch setting to maintain the previous behavior. I will now close this issue. If you require further support with annotation generation, please feel free to open a new issue at https://github.com/redhat-developer/vscode-java/issues

**Closed by testforstephen** 2023-08-29 06:49 UTC
Labels: annotation-processing

**Comment by kjq** [comment] 2023-08-29 11:31
At a quick glance this seems to work for now.  Thank you, it is very appreciated!
