### ISSUE TITLE
Java Code runs on jGrasp but not on VS Code

### ISSUE THREAD

**Issue by AGoh2019** [microsoft/vscode-java-debug#1493] opened 2024-06-26 04:03 UTC
Type: <b>Bug</b>

- Using Oracle Java SE Kit 21.0.2 (64-bit)
- Enter java code
- Run Java
- Churns up error // while on jGrasp it compiles successfully
- Run java file  // Sometimes it returns error in VS Code, otherwise it executes successfully.
PLEASE CHECK THE MICROSOFT JAVA OR ORACLE PLUGINS OR IS IT SOMETHING IN THE JDK THAT IS NOT RIGHT.  I CAN'T FIGURE UP WHAT IS WRONG.

And don't tell me to report to the right authorities.  I am not a developer but more of a data analyst, and I cannot tolerate errors if I am going to run code using Python, R, Julia etc.

Extension version: 0.57.0
VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (6.78GB free)|
|Process Argv|--crash-reporter-id 3ab84b27-3b66-48e1-b94b-f4055dc42152|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
legacy_priority:31082724

```

</details>

**Comment by testforstephen** [comment] 2024-07-12 07:56
pls provide the sample code that does not work on VS Code but fine on jGrasp.

**Comment by AGoh2019** [comment] 2024-07-12 12:49
I believe the Java plugin was updated.
--- Andrew Goh
 

    On Friday, 12 July 2024 at 03:57:13 pm SGT, Jinbo Wang ***@***.***> wrote:  
 
 


pls provide the sample code that does not work on VS Code but fine on jGrasp.

**Comment by testforstephen** [comment] 2024-07-15 03:20
May I understand that it works well in the latest Java extensions?

**Comment by AGoh2019** [comment] 2024-07-15 03:58
Yes, it works well, unless the Java plugin does not support the use of packages?
--- Andrew Goh
 

    On Monday, 15 July 2024 at 11:20:23 am SGT, Jinbo Wang ***@***.***> wrote:  
 
 


May I understand that it works well in the latest Java extensions?

**Comment by testforstephen** [comment] 2024-07-15 05:19
Close it since it works. If you have further issue, feel free to create a new issue with the sample project to reproduce the problem.

**Closed by testforstephen** 2024-07-15 05:19 UTC
