### ISSUE TITLE
Request textDocument/codeAction failed

### ISSUE THREAD

**Issue by bsaby** [microsoft/vscode-java-debug#283] opened 2018-04-23 09:42 UTC
##### Environment
- Operating System: Win10
- JDK version: JDK-10.0.1
- Visual Studio Code version: 1.22.2
- Java extension version: 0.23.0
- Java Debugger extension version: 0.8.0 (build246)

##### Steps To Reproduce
1. Open project 24.hotCodeReplace in vscode.
2. Set breakpoints: NameProvider.java line 12; Person.java line 13
3. Press F5 to start debug.
4. The program stopped at the Person.java line 13, change the value of the line "old" to "new"
5. Save the document 
##### Current Result
Sometimes, error output in Language support for java 

[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
![image](https://user-images.githubusercontent.com/22470312/39119072-8c90ee00-471d-11e8-82ec-94f495a9964a.png)

**Comment by testforstephen** [comment] 2021-12-02 04:39
Cannot reproduce it in latest VS Code, closing it.

**Closed by testforstephen** 2021-12-02 04:39 UTC
Labels: external
