### ISSUE TITLE
Debug hangs and never really connects

### ISSUE THREAD

**Issue by mojo2012** [Microsoft/vscode-java-debug#224] opened 2018-01-26 18:40 UTC
I have the latest VSCode and the latest version of the java extension(s).
This is my launch.json:
```
        {
            "type": "java",
            "name": "Debug (localhost)",
            "request": "attach",
            "hostName": "localhost",
            "port": 8000
        }
```
The progress bar below the debug button spins forever, but the debugger never connects to the running process.
When using the same configuration with Eclipse, it immediately connects and I get a log message, that a debugger has connected on port 8000 (so the JVM is configured correctly).

In the dev console I get the following error:
```
console.ts:123 [IPC Library: Search] (node:21948) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
```

##### Environment
- Operating System: macOS 10.13.2 (17C205)
- JDK version: Java(TM) SE Runtime Environment (build 1.8.0_112-b16) (using DCEVM)
- Visual Studio Code version:  1.19.3 (1.19.3)
- Java extension version: 0.2.0
- Java Debugger extension version:

**Comment by akaroml** [comment] 2018-03-02 03:47
@mojo2012 thanks for reporting. Unfortunately, I'm not able to reproduce this issue with limited info. In attach scenario, the debuggee program needs to be launched by a user before the debugger can attach to it. Please help double check:
1. Is the debuggee program already launched?
2. Is the firewall blocking the debugger from connecting?
3. Other factors that could affect the attaching process.

**Comment by mojo2012** [comment] 2018-03-02 07:32
I will try to gather more data and report back

**Comment by andxu** [comment] 2018-03-15 08:01
@mojo2012 What is going on now, can you reproduce this problem?

**Comment by mojo2012** [comment] 2018-03-15 08:02
Sorry I didn't have any time yet, I'll try to post an update the next days

**Comment by mojo2012** [comment] 2018-05-08 11:37
I completely removed vscode and all settings and recreated my configuration - now it works. Somehow my vscode was messed up. Can be closed!

**Comment by andxu** [comment] 2018-05-08 12:38
Glad to see your reply, please feel free to address new issue when you meet problems. Close this one as it is considered to be resolved

**Closed by andxu** 2018-05-08 12:38 UTC
Labels: needs more info
