### ISSUE TITLE
An error show the message "A JNI error has occured, please check your installation and try again"

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/vscode-java-debug#765] opened 2020-02-19 10:56 UTC
##### Environment
- Operating System: Mac
- JDK version: JDK11
- Visual Studio Code version: 1.42.1
- Java extension version: 0.56.0
- Java Debugger extension version: 0.25.0

##### Steps To Reproduce
1. Git clone https://github.com/microsoft/vscode-java-debug.git
2. Open 26.environmentvariable project under testprojects
3. F5 to start.

##### Current Result
![image](https://user-images.githubusercontent.com/51812626/74827299-26af6100-5348-11ea-817b-974b5787777c.png)

##### Expected Result
Should not have this issue.

**Comment by testforstephen** [comment] 2020-02-19 11:01
`this version of the Java Runtime only recognizes class file version up to 52.0`, this reflects your java home resolved by the extension is jdk 8, not the JDK 11. Please check how did you set the java home in your environment?

**Comment by testforstephen** [comment] 2020-02-20 08:31
There is a warning for this project:
![image](https://user-images.githubusercontent.com/14052197/74914996-6afd3880-53fe-11ea-9003-ba076d493d92.png)

The root cause is the language server didn't use the correct compiler compliance to build the project, it will cause the generated .class files cannot be launched by the project's Java runtime.

Opened an issue in vscode-java extension. https://github.com/redhat-developer/vscode-java/issues/1290

**Closed** 2020-02-20 08:32 UTC
Labels: external
