### ISSUE TITLE
show variable value at top level

### ISSUE THREAD

**Issue by mentaloaf** [microsoft/vscode-java-debug#787] opened 2020-04-06 08:56 UTC
In the variables pane in the debugger, it requires additional effort to see information about different object variables which are usually available/presented in other debuggers.  Examples of this are:

- if the variable is an integer object, show the integer value at the top level rather than "Integer@44" where you have to expand this to see tha actual integer value (which is most cases is all you care about)
- show a human readable date for a Date object at the highest level.  Even if you drill down into a date you get an epoch milliseconds value that you then have to manually convert to a human readable string when in most cases all you wanted to see was the actual human readable date without having to expand the variable
- for data structures, show the size of the structure and allow access into the elements at the highest level rather than having to dig deep down into the obscure structure of the Java object low level implementation

I have also never gotten hover over a variable to show its value in a tooltip - not sure if this works under certain circumstances.  Would be great if the variables toString method was called on hover to see something meaningful.

Thanks!
Jon

**Comment by testforstephen** [comment] 2020-04-07 01:44
These are all supported. Could you tell me what's your debugger version and share us a sample project to reproduce it?

![image](https://user-images.githubusercontent.com/14052197/78621072-411baa80-78b4-11ea-894e-eadde9f488f2.png)

**Comment by mentaloaf** [comment] 2020-04-07 07:45
Hello.

Yes I am using debugger version 0.25.1:



The attached project reproduces the problem in my environment (macOS 10.14.6, vscode version 1.43.2):



As you can see when I hover and in the debugger side bar I don’t get the information I would like to see:



Thanks!
Jon

**Comment by testforstephen** [comment] 2020-04-07 08:11
Cannot see your email attachment in the github issue comment, please attach it again.

**Comment by mentaloaf** [comment] 2020-04-07 08:50
Attaching files again on GitHub.

[vscode_debugger_example.zip](https://github.com/microsoft/vscode-java-debug/files/4443026/vscode_debugger_example.zip)
![PastedGraphic-6](https://user-images.githubusercontent.com/22648656/78649327-fcaef100-7858-11ea-9cd7-b824002fad33.png)
![PastedGraphic-4](https://user-images.githubusercontent.com/22648656/78649332-fe78b480-7858-11ea-8c05-55ae9a594b44.png)
![PastedGraphic-5](https://user-images.githubusercontent.com/22648656/78649334-ff114b00-7858-11ea-91f4-c2ee9129ee08.png)

**Comment by testforstephen** [comment] 2020-04-08 07:58
Works in my side. Make sure enable the user setting `java.debug.settings.showToString`.

![image](https://user-images.githubusercontent.com/14052197/78758779-3b57bf00-79b1-11ea-99fd-4a66284c0cd2.png)

If it still doesn't work, then please share the log to see whether there is any exception. Below is the command to get the log file:
**F1** -> **Java: Open the Java language server log file**

**Comment by mentaloaf** [comment] 2020-04-10 02:48
Bummer.  Hovers and variable side panel don't show values for me and showToString is (and has been) set to true.  Can you see anything wrong in my config?  Would be really nice to be able to see what you're seeing!
![VSCodeJavaDebuggerSettings](https://user-images.githubusercontent.com/22648656/78957766-f3549d00-7a81-11ea-815e-81a5267f36f0.png)

**Comment by mentaloaf** [comment] 2020-04-10 02:51
Attaching the Java language server log file here.

Thanks!
[vscode_java_language_log.txt](https://github.com/microsoft/vscode-java-debug/files/4459659/vscode_java_language_log.txt)

**Comment by testforstephen** [comment] 2020-04-10 03:00
I found an exception in the log.

```
!ENTRY java-debug 4 0 2020-04-09 15:14:28.001
!MESSAGE Multiple projects are valid for evaluation.

!ENTRY java-debug 4 0 2020-04-09 15:14:28.003
!MESSAGE [error response][evaluate]: Cannot evaluate because of java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json..
!STACK 0
com.microsoft.java.debug.core.DebugException: Cannot evaluate because of java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json..
	at com.microsoft.java.debug.core.adapter.AdapterUtils.createCompletionException(AdapterUtils.java:255)
	at com.microsoft.java.debug.core.adapter.handler.EvaluateRequestHandler.lambda$handle$0(EvaluateRequestHandler.java:141)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1771)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1763)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json.
	at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.findJavaProjectByType(JdtEvaluationProvider.java:306)
	at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.ensureDebugTarget(JdtEvaluationProvider.java:413)
	at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.evaluate(JdtEvaluationProvider.java:140)
	at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.evaluate(JdtEvaluationProvider.java:115)
	at com.microsoft.java.debug.core.adapter.handler.EvaluateRequestHandler.lambda$handle$0(EvaluateRequestHandler.java:83)
	... 7 more
```

Could you try to delete _.vscode/launch.json_? If it still doesn't work, then try **F1** -> **Java: Clean the Java language server workspace** command.

**Comment by mentaloaf** [comment] 2020-04-13 02:13
Hello.

Removing the launch.json fixed my example project when I let vscode create the launch entry for me.  However, when I tried to start over with just one debug config from my old launch.json it didn’t work.  After reading the error (doh) I added the projectName field to my config and then it works.  I assume that field is required.  Anyway really appreciate the help!

Thanks!
Jon

**Comment by testforstephen** [comment] 2021-09-23 07:54
Since the issue has been resolved, i will close it.

**Closed by testforstephen** 2021-09-23 07:54 UTC
